from google.adk.agents.sequential_agent import SequentialAgent
from google.adk.agents.llm_agent import LlmAgent
from google.adk.models import LiteLlm
import json
import os

# --- Constants ---
LOCAL_MODEL = LiteLlm(model='ollama/llama3.1:latest')

# --- Tools ---
def read_test_json_text_only() -> str:
    """Reads the EXIST 2026 test JSON file and returns its content WITHOUT physiological sensor data."""
    file_path = "/Users/aryan/Desktop/aryan_Exist_2026_dataset/EXIST_2026_TESTING/EXIST_2026_Memes_Dataset/test/EXIST2026_test_clean.json"
    if not os.path.exists(file_path):
        return f"Error: File not found at {file_path}"
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            truncated_data = {}
            for k in list(data.keys())[:2]:  # Testing on 2 items to avoid context explosion
                item = data[k].copy()
                if "sensorial" in item:
                    del item["sensorial"]
                truncated_data[k] = item
            return json.dumps(truncated_data)
    except Exception as e:
        return f"Error reading JSON: {str(e)}"

def read_test_json_sensors_only() -> str:
    """Reads the EXIST 2026 test JSON file and returns ONLY the physiological sensor data."""
    file_path = "/Users/aryan/Desktop/aryan_Exist_2026_dataset/EXIST_2026_TESTING/EXIST_2026_Memes_Dataset/test/EXIST2026_test_clean.json"
    if not os.path.exists(file_path):
        return f"Error: File not found at {file_path}"
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            sensor_data = {}
            for k in list(data.keys())[:2]:
                if "sensorial" in data[k]:
                    sensor_data[k] = {"sensorial": data[k]["sensorial"]}
            return json.dumps(sensor_data)
    except Exception as e:
        return f"Error reading JSON: {str(e)}"

# --- Pre-load Data to avoid LLM tool-calling issues ---
TEXT_DATA = read_test_json_text_only()
SENSOR_DATA = read_test_json_sensors_only()

# --- 1. Define Sub-Agents for Each Pipeline Stage ---

# Agent 1: Initial JSON Analyzer
# Takes the location/content of the JSON testing data and provides initial scores.
json_analyzer_agent = LlmAgent(
    name="JSONAnalyzerAgent",
    model=LOCAL_MODEL,
    instruction=f"""
    You are an expert sociolinguistic annotator specialised in detecting sexism in online media.
    
    Here is the testing data you must review:
    ```json
    {TEXT_DATA}
    ```
    
    Output Requirements:
    Provide your final assessment as a direct response.
    Include an initial 'hard_score' (categorical label like 'YES'/'NO') 
    and a 'soft_score' (confidence probability between 0.0 and 1.0) for the provided items.
    """,
    description="Analyzes the input JSON test file and provides initial hard and soft scores.",
    output_key="initial_scores"
)

# Agent 2: Score Refiner
# Takes the initial scores and provides a secondary evaluation or refinement based on other criteria.
score_refiner_agent = LlmAgent(
    name="ScoreRefinerAgent",
    model=LOCAL_MODEL,
    instruction="""
    You are an expert model calibrator.
    You will be provided with the original context and the `initial_scores` generated by the previous agent:
    
    ```json
    {initial_scores}
    ```
    
    Your task is to review these scores and refine the score. Consider potential edge cases, linguistic nuances (such as sarcasm, irony, or implied meaning), or secondary tasks, and refine the hard and soft scores.
    
    Output:
    Provide the refined 'hard_score' and 'soft_score' based on your secondary evaluation.
    """,
    description="Reviews and refines the initial hard and soft scores.",
    output_key="refined_scores"
)

# Agent 3: Sensor Fusion & Final JSON Generator
# Fuses the refined scores with physiological sensor data to output the final JSON file.
sensor_fusion_agent = LlmAgent(
    name="SensorFusionAgent",
    model=LOCAL_MODEL,
    instruction=f"""
    You are an expert in physiological signals and computational sexism detection.
    You are given:
    1. Soft classification scores from a Vision-Language Model (VLM) for a meme (these are the `refined_scores` from previous stages):
    ```json
    {{refined_scores}}
    ```
    2. Physiological sensor readings from real humans who viewed the same meme:
    ```json
    {SENSOR_DATA}
    ```

    Your task: Adjust the confidence scores based on what the sensor data tells us
    about how the human body actually reacted to this meme.

    SENSOR INTERPRETATION RULES:
    - HIGH arousal_score (>0.65): Body was disturbed -> confidence this is sexist should increase
    - LOW arousal_score (<0.35): Body was calm -> confidence should decrease  
    - MEDIUM (0.35-0.65): No strong signal -> keep VLM score mostly unchanged

    WHAT EACH SENSOR MEASURES:
    - et_reaction_time_ms: Time to decide (ms). >12000=hesitation=disturbed, <5000=quick/unbothered
    - hr_std: Heart rate variability. >1.5=emotional turbulence, <0.8=calm
    - et_pupil_left_mean_mm: Pupil dilation. >3.5mm=high load, <2.5mm=low load
    - eeg_theta_mean: Brain emotional processing. >0.5=triggered, near 0=neutral
    - et_fixations_count: Gaze fixations. >45=intensive study, <15=quick glance

    ADJUSTMENT RULES:
    - Only adjust by maximum +-0.20 from the original score

    Output the final hard and soft score of the meme, and other task results, formatted strictly as the JSON structure required for submission.
    Output *only* the complete final JSON block, enclosed in triple backticks (```json ... ```).
    """,
    description="Fuses sensor data with cumulative scores and generates the final JSON output.",
    output_key="final_json"
)

# --- 2. Create the SequentialAgent ---
# Orchestrates the pipeline by running the sub_agents in order.
sexism_pipeline_agent = SequentialAgent(
    name="SexismDetectionPipelineAgent",
    sub_agents=[json_analyzer_agent, score_refiner_agent, sensor_fusion_agent],
    description="A sequential pipeline that analyzes JSON data, refines scores, fuses sensor data, and outputs final JSON predictions.",
)

# Set the root agent for the ADK
root_agent = sexism_pipeline_agent
